lcl:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sqldb
    username: root
    password: "1412613528."
  alioss:
    bucket-name: xuan20235
    access-key-id: LTAI5t7aBWbBp1Gm6hQ5wwt4
    access-key-secret: tjIaJm39g0dPsY8Iei0pGuo6QnrL5Q
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: 101.34.80.19
    port: 6379
    password: "1412613528."
    database: 3
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 100