server:
  port: 8088

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${lcl.datasource.driver-class-name}
      url: jdbc:mysql://${lcl.datasource.host}:${lcl.datasource.port}/${lcl.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${lcl.datasource.username}
      password: ${lcl.datasource.password}
  redis:
    host: ${lcl.redis.host}
    port: ${lcl.redis.port}
    password: ${lcl.redis.password}
    database: ${lcl.redis.database}
    lettuce:
      pool:
        max-active: ${lcl.redis.lettuce.pool.max-active}
        max-idle: ${lcl.redis.lettuce.pool.max-idle}
        min-idle: ${lcl.redis.lettuce.pool.min-idle}
        max-wait:  ${lcl.redis.lettuce.pool.max-wait}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lcl.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: off
    com:
      lcl:
        mapper: off
        service: off
        controller: off


lcl:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
    endpoint: ${lcl.alioss.endpoint}
    access-key-secret: ${lcl.alioss.access-key-secret}
    access-key-id: ${lcl.alioss.access-key-id}
    bucket-name: ${lcl.alioss.bucket-name}



